### ISSUE TITLE
Allow the editor windows to  increase size

### ISSUE THREAD

**Issue by labra** [weso/rdfshape#193] opened 2020-11-25 08:45 UTC
It would be great if a user could extend/decrease the size of the editor windows of RDF/ShEx/SHACL/etc.

**Comment by ulitol97** [comment] 2020-11-26 10:01
This looks like a duplicate of [https://github.com/weso/rdfshape-client/issues/41](https://github.com/weso/rdfshape-client/issues/41) and the issue is more suited for the client repository.

**Closed by ulitol97** 2020-11-26 10:01 UTC
